images_dir: /Users/mukund/orgpedia/cabsec2/import/images
ignore_docs: [ ]
pipeline:
  - name: website_language_generator
    config:
      conf_stub: 'website_language_generator'
      languages: ['en']


  - name: html_generator2
    config:
      image_root: /Users/mukund/orgpedia/cabsec2/import/images
      html_root: output/new-svgs
      color_dict:
        officer: blue
        post: green
        #order_date: red order_date is currently not a region
      
  
