description: This pipeline generates html that is available on www.orgpedia.in, the html goes through series of compressions first tailwind CSS is minified and then html is minified (check [makefile](makefile)).
images_dir: /Users/mukund/orgpedia/cabsec2/import/images
ignore_docs: [ ]
pipeline:
  - name: website_language_generator
    config:
      conf_stub: 'website_language_generator'
      languages: ['en']
      officer_info_files: ['conf/wiki_officer_images.yml']

  - name: detail_language_generator
    config:
      conf_stub: 'website_language_generator'
      languages: ['en']
      officer_info_files: ['conf/wiki_officer_images.yml']

  # - name: html_generator
  #   config:
  #     image_root: ../../images
  #     html_root: output/pages
  #     svg_stem: or
  #     color_dict:
  #       officer: blue
  #       post: green
  #       #order_date: red order_date is currently not a region


#  - name: html_generator2
#    config:
#      image_root: '.' #../../images
#      svg_root: output/pages
#      css_file: ../../c/svg.css
#      svg_stem: d
#
